### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by neon-ninja** [castelao/supportdata#2]
Steps to reproduce:

`import supportdata; supportdata.download_file(".", "https://raw.githubusercontent.com/castelao/supportdata/master/requirements.txt")`

output:
Downloading: requirements.txt (25 bytes)
        25 [100.00%]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\supportdata\supportdata.py",
line 102, in download_file
    shutil.copy(f.name, fname)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ADMINI~1\\AppData\\Lo
cal\\Temp\\2\\tmpy3azqrwr'

As per https://docs.python.org/2/library/tempfile.html "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)"

Setting delete=False seems to solve this issue

**Comment by castelao** [comment]
Hi @neon-ninja , I'm sorry for the late reply. It seems like recently I lost a couple of alerts from GitHub. Luckily another user contacted me reporting the same problem. I'm about to release a new version that fixes this.

I rather don't use the delete=False so we don't risk to keep garbage in the temporary directory.

Thank you!
